#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine to install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
