#!/usr/bin/env bash
# installing nginx with custom header coniguration in both web-01 and web-02

sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
set_header='add_header X-Served-By 257227-web-02;'
sudo sed -i '/location \/ {/a '"$set_header" /etc/nginx/sites-available/default
sudo service nginx restart
