#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install -y haproxy
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
    	backend web-backend
	balance roundrobin
	server 257227-web-01 3.90.84.234 check
	server 257227-web-02 100.25.222.100 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
