#!/usr/bin/env bash
# printing fizzbuzz

i=1
while ((i <= 100))
do
	if ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	elif ((i % 5 == 0) && (i % 3 == 0))
	then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	((i++))
done
