#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server

cp /etc/hosts ~/hosts_cpy
echo "127.0.0.2	localhost" > hosts_cpy
echo "8.8.8.8 facebook.com" >> hosts_cpy
cp ~/hosts_cpy /etc/hosts
